---
- name: Patch kube-proxy strict ARP
  ansible.builtin.shell: |
    kubectl --kubeconfig /etc/kubernetes/admin.conf get configmap kube-proxy -n kube-system -o yaml | \
    sed -e "s/strictARP: false/strictARP: true/" | \
    kubectl apply --kubeconfig /etc/kubernetes/admin.conf -f - -n kube-system

- name: Copy metallb-native manifest directory to host
  ansible.builtin.template:
    src: "metallb-native.yaml.j2"
    dest: "/tmp/metallb-native.yaml"

- name: Wait for kube-system pods to be ready
  ansible.builtin.shell: kubectl --kubeconfig /etc/kubernetes/admin.conf wait -n kube-system --all pods --for=condition=Ready --timeout=5m

- name: Apply metallb-native
  ansible.builtin.shell: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f /tmp/metallb-native.yaml

- name: Wait for Readiness of metallb-native
  ansible.builtin.shell: kubectl --kubeconfig /etc/kubernetes/admin.conf wait -n metallb-system --all pods --for=condition=Ready --timeout=5m

- name: Copy metallb ip pools & advertisement manifest
  ansible.builtin.template:
    src: "vips.yml.j2"
    dest: "/tmp/vips.yml"

- name: Apply metallb ip pools
  ansible.builtin.shell: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f /tmp/vips.yml
