- hosts: control_planes[0]
  gather_facts: yes
  become: yes
  roles:
    - role: kubernetes/scale_cilium
      when: kube_cni == 'cilium' and groups['control_planes']|length > 1

- hosts: all,!container_registry # All except the CR
  gather_facts: yes
  become: yes
  roles:
    - cleanup_hosts
