---
- hosts: all
  gather_facts: no
  become: yes
  roles:
    - install_ssl_deps

- hosts: all,!container_registry # All except the CR
  gather_facts: yes
  become: yes
  roles:
    - update_hosts

- hosts: ca_server
  gather_facts: yes
  become: yes
  roles:
    - create_ca

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - generate_ssl

- hosts: container_registry
  gather_facts: yes
  become: yes
  roles:
    - docker
    - container_registry

- hosts: control_planes
  gather_facts: yes
  become: yes
  roles:
    - role: haproxy_keepalived
      when: groups['control_planes']|length > 1

- hosts: control_planes,nodes
  gather_facts: yes
  become: yes
  roles:
    - disable_swap
    - kubernetes/install_deps
    - kubernetes/preconfig_nodes

- hosts: control_planes
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/pull_images

- hosts: control_planes[0]
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/main_control_plane
    - kubernetes/cni

- hosts: control_planes[1:]
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/join_control_plane

- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/join_workers

- hosts: control_planes[0]
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/metallb
    - kubernetes/storage
    - role: kubernetes/scale_cilium
      when: kube_cni == 'cilium' and groups['control_planes']|length > 1

- hosts: all,!container_registry # All except the CR
  gather_facts: yes
  become: yes
  roles:
    - cleanup_hosts

